### ISSUE TITLE
Update topology colours

### ISSUE THREAD

**Issue by anuragbhatia** [anuragbhatia/INNOG-IPv6-Mikrotik-workshop#16]
@rahulmkhj As discussed previously on call with @vijayahire07 please change colour for topology. 

Topology is originally on Google Drawings [here](https://docs.google.com/drawings/d/1X8GMv4QgQhhsmPrMTIUtTaYSeIQi3JXxl8D5yRTZpPI/edit?usp=sharing)

Please consider following change: 

1. R1,R3,R6,R8 etc get a specific set of colour
2. R2,R4,R7,R9 etc get another specific set of colour
3. R5, R10, R15 etc get another specific set of colour
4. Document meaning of colours. You can use space on bottom right side to put R1/R3/R6 etc as local ISP, R2/R4/R7 as regional ISP and R5/R10/R15 as large global ISP.
5. Please also define (somehow!) that R2-R4 , R7-R9 etc are peers and thus attendees will be required to tweak filters accordingly.

**Comment by rahulmkhj** [comment]
Updated the topology with colors to reflect different levels of imaginary ISPs. 

Also tweaked it to look a little more consistent in terms of alignment & spacing.
