### ISSUE TITLE
P2P link mapping for each R router

### ISSUE THREAD

**Issue by anuragbhatia** [anuragbhatia/INNOG-IPv6-Mikrotik-workshop#9]

**Comment by anuragbhatia** [comment]
Created. 

Assigning to @rahulmkhj so he can review. Playbook is generated using semi-automation/scripts. Needs to be cross checked for port mapping. 

@rahulmkhj Please compare topology [here](https://github.com/anuragbhatia/INNOG-IPv6-Mikrotik-workshop/wiki/Topology) with the playbook [here](https://github.com/anuragbhatia/INNOG-IPv6-Mikrotik-workshop/blob/main/Playbooks/Networks/04p2p.yml). 

Also remember that ether1 is internet always (even when disabled, ether2 is management and ether3 is link to CPE for all except GW router). More information about that [here](https://github.com/anuragbhatia/INNOG-IPv6-Mikrotik-workshop/wiki/Provider-Router).

**Comment by rahulmkhj** [comment]
Verified & Confirmed. The playbook is in accordance with the topology.

**Caution: The playbooks need to run in the correct order for ports to be mapped correctly.** ( [issue opened](https://github.com/anuragbhatia/INNOG-IPv6-Mikrotik-workshop/issues/13) )
